package io.mailmite.core;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Generates a self-contained, vulnerability-centric HTML report from an
 * {@link AnalysisReport}. Output file: {@code outputDir/report.html}
 *
 * <p>Layout (top to bottom):
 * <ol>
 *   <li>Header — bundle id, executable, scan id, generation timestamp</li>
 *   <li>Risk dashboard — severity stat tiles + counts per MSTG category</li>
 *   <li>Bundle &amp; signing — Team ID, Swift flag, architectures, provisioning</li>
 *   <li><b>Vulnerabilities</b> — every finding rendered as a full card with
 *       description, affected, evidence, PoC, remediation, reference</li>
 *   <li>LLM raw findings (collapsible) — only when LLM was enabled</li>
 *   <li>Code surface (collapsible) — entry points + class index, summary only</li>
 *   <li>Sample strings (collapsible) — small sample, not full dump</li>
 * </ol>
 */
public final class HtmlReporter {

    private static final int MAX_STRINGS_DISPLAY = 30;
    private static final int MAX_CLASSES_DISPLAY = 25;

    private HtmlReporter() {}

    public static Path generate(AnalysisReport r, Path outputDir) throws IOException {
        StringBuilder h = new StringBuilder();
        h.append(headHtml(r));

        // 1. header
        h.append(headerCard(r));

        // 2. risk dashboard (severity dashboard + by-category)
        h.append(riskDashboard(r));

        // 3. bundle / signing
        h.append(bundleCard(r));

        // 4. VULNERABILITIES (the centrepiece)
        h.append(vulnerabilitiesSection(r));

        // 4b. Suppressed findings (false-positives / fixed) — for audit trail
        h.append(suppressedSection(r));

        // 5. LLM raw findings (only if any with severity)
        h.append(llmRawSection(r));

        // 6. code surface (collapsible, compact)
        h.append(codeSurfaceSection(r));

        // 7. sample strings (collapsible)
        h.append(stringsSampleSection(r));

        // footer
        h.append("<footer>Generated by <strong>Mailmite</strong> ")
         .append(" &middot; scan id <code>").append(esc(r.scanId())).append("</code>")
         .append(" &middot; duration ").append(r.durationMs()).append(" ms")
         .append("</footer>");

        h.append("</main></body></html>");

        Path out = outputDir.resolve("report.html");
        Files.writeString(out, h.toString());
        return out;
    }

    // ── head + global styles ──────────────────────────────────────────────────

    private static String headHtml(AnalysisReport r) {
        return """
            <!DOCTYPE html>
            <html lang="en">
            <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width,initial-scale=1">
            <title>Mailmite Security Report — """ + esc(r.bundleIdentifier() == null ? r.bundleExecutable() : r.bundleIdentifier()) + """
            </title>
            <style>
            *,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
            :root{
              --bg:#f6f7fa;--surface:#fff;--border:#e2e4e9;--text:#1a1d23;
              --muted:#6b7280;--accent:#5571f7;--accent-h:#3d56e0;
              --crit:#9d174d;--crit-bg:#fce7f3;
              --high:#dc2626;--high-bg:#fee2e2;
              --med:#d97706;--med-bg:#fef3c7;
              --low:#2563eb;--low-bg:#dbeafe;
              --info:#6b7280;--info-bg:#f3f4f6;
              --green:#16a34a;--green-bg:#dcfce7;
            }
            body{font-family:system-ui,-apple-system,sans-serif;background:var(--bg);color:var(--text);font-size:14px;line-height:1.5}
            main{max-width:1180px;margin:0 auto;padding:1.5rem}
            h1{font-size:1.5rem;margin-bottom:.25rem}
            h2{font-size:1.05rem;font-weight:700;margin-bottom:.85rem;color:var(--text)}
            a{color:var(--accent);text-decoration:none}
            a:hover{text-decoration:underline}
            code{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:.85em;background:var(--info-bg);padding:.05rem .35rem;border-radius:3px}

            /* cards */
            .card{background:var(--surface);border:1px solid var(--border);border-radius:8px;padding:1.1rem 1.3rem;margin-bottom:1rem;box-shadow:0 1px 3px rgba(0,0,0,.04)}
            .card-meta{font-size:.78rem;color:var(--muted);margin-bottom:.35rem;text-transform:uppercase;letter-spacing:.05em;font-weight:600}

            /* header */
            .hero{background:linear-gradient(135deg,#5571f7,#3d56e0);color:#fff;border:none}
            .hero h1{color:#fff}
            .hero p{color:#dde4ff;font-size:.875rem}
            .hero-meta{margin-top:.5rem;font-size:.78rem;opacity:.85}

            /* severity dashboard */
            .sev-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:.6rem}
            @media(max-width:680px){.sev-grid{grid-template-columns:repeat(2,1fr)}}
            .sev-tile{border-radius:6px;padding:.65rem .85rem;text-align:left;border:1px solid transparent}
            .sev-tile .v{font-size:1.7rem;font-weight:800;line-height:1}
            .sev-tile .l{font-size:.72rem;font-weight:700;text-transform:uppercase;letter-spacing:.05em;margin-top:.25rem}
            .sev-critical{background:var(--crit-bg);color:var(--crit);border-color:#fbcfe8}
            .sev-high{background:var(--high-bg);color:var(--high);border-color:#fecaca}
            .sev-medium{background:var(--med-bg);color:var(--med);border-color:#fde68a}
            .sev-low{background:var(--low-bg);color:var(--low);border-color:#bfdbfe}
            .sev-total{background:#eef2ff;color:#3730a3;border-color:#c7d2fe}
            .sev-zero{background:var(--green-bg);color:var(--green);border-color:#bbf7d0}

            /* category chips */
            .cats{display:flex;flex-wrap:wrap;gap:.4rem;margin-top:.9rem}
            .chip{font-size:.72rem;background:var(--info-bg);color:var(--muted);padding:.2rem .6rem;border-radius:999px;font-weight:600}
            .chip strong{color:var(--text)}

            /* bundle info */
            .kv{display:grid;grid-template-columns:160px 1fr;gap:.35rem .75rem;font-size:.82rem}
            .kv-key{color:var(--muted);font-weight:500}
            .kv-val{word-break:break-all}

            /* badges */
            .badge{display:inline-block;padding:.15rem .55rem;border-radius:999px;font-size:.7rem;font-weight:700;text-transform:uppercase;letter-spacing:.04em}
            .badge-critical{background:var(--crit-bg);color:var(--crit)}
            .badge-high{background:var(--high-bg);color:var(--high)}
            .badge-medium{background:var(--med-bg);color:var(--med)}
            .badge-low{background:var(--low-bg);color:var(--low)}
            .badge-info{background:var(--info-bg);color:var(--info)}
            .badge-mstg{background:#eef2ff;color:#4338ca}
            .badge-llm{background:#fef3c7;color:#92400e}

            /* vuln cards */
            .vuln{background:var(--surface);border:1px solid var(--border);border-left:4px solid;border-radius:6px;padding:1rem 1.2rem;margin-bottom:.75rem;box-shadow:0 1px 2px rgba(0,0,0,.03)}
            .vuln.critical{border-left-color:var(--crit)}
            .vuln.high{border-left-color:var(--high)}
            .vuln.medium{border-left-color:var(--med)}
            .vuln.low{border-left-color:var(--low)}
            .vuln-head{display:flex;align-items:flex-start;gap:.6rem;flex-wrap:wrap;margin-bottom:.7rem}
            .vuln-title{font-weight:700;font-size:1rem;flex:1;min-width:0}
            .vuln-meta{display:flex;flex-wrap:wrap;gap:.4rem;font-size:.72rem;color:var(--muted);align-items:center}
            .vuln-cvss{background:var(--info-bg);padding:.15rem .5rem;border-radius:3px;font-weight:700}
            .vuln-rule{font-family:ui-monospace,monospace;color:var(--muted);font-size:.72rem;font-weight:600}
            .vuln-section{margin-top:.85rem}
            .vuln-section-title{font-size:.7rem;font-weight:700;color:var(--muted);text-transform:uppercase;letter-spacing:.05em;margin-bottom:.3rem}
            .vuln-section p{font-size:.85rem;line-height:1.55}
            .vuln-grid{display:grid;grid-template-columns:1fr 1fr;gap:.85rem}
            @media(max-width:720px){.vuln-grid{grid-template-columns:1fr}}
            pre.code{background:#111;color:#e2e8f0;padding:.6rem .8rem;border-radius:5px;font-family:ui-monospace,monospace;font-size:.72rem;white-space:pre-wrap;word-break:break-word;max-height:240px;overflow-y:auto}
            pre.poc{background:#0c1a2b;color:#bcd9ff}

            /* collapsible sections */
            details{background:var(--surface);border:1px solid var(--border);border-radius:8px;padding:0;margin-bottom:1rem}
            details > summary{cursor:pointer;padding:.85rem 1.2rem;font-weight:700;color:var(--text);font-size:.95rem;list-style:none}
            details > summary::-webkit-details-marker{display:none}
            details > summary::before{content:'▸ ';color:var(--muted);font-size:.85em}
            details[open] > summary::before{content:'▾ '}
            details > summary > .secondary{color:var(--muted);font-weight:500;font-size:.8rem;margin-left:.5rem}
            details > .details-body{padding:0 1.2rem 1rem}

            /* class index */
            .class-grid{display:grid;grid-template-columns:1fr 1fr;gap:.3rem;font-size:.78rem;font-family:ui-monospace,monospace}
            @media(max-width:600px){.class-grid{grid-template-columns:1fr}}
            .class-row{padding:.3rem .5rem;background:var(--bg);border-radius:4px;display:flex;justify-content:space-between;gap:.5rem}
            .class-row .n{color:var(--muted);font-size:.7rem}

            /* tables */
            table{width:100%;border-collapse:collapse;font-size:.78rem;margin-top:.5rem}
            th,td{padding:.4rem .7rem;text-align:left;border-bottom:1px solid var(--border)}
            th{background:var(--bg);font-weight:700;color:var(--muted);font-size:.7rem;text-transform:uppercase;letter-spacing:.04em}
            td.mono{font-family:ui-monospace,monospace;font-size:.72rem}

            /* empty state */
            .empty{text-align:center;padding:2rem;color:var(--muted);font-size:.875rem}
            .empty-good{color:var(--green);font-weight:600}

            /* footer */
            footer{text-align:center;color:var(--muted);font-size:.72rem;margin:2rem 0 .5rem}
            </style>
            </head>
            <body><main>
            """;
    }

    // ── header card ───────────────────────────────────────────────────────────

    private static String headerCard(AnalysisReport r) {
        StringBuilder h = new StringBuilder();
        h.append("<div class='card hero'>");
        h.append("<div class='card-meta' style='color:#dde4ff'>Security Assessment Report</div>");
        h.append("<h1>").append(esc(r.bundleIdentifier() == null ? r.bundleExecutable() : r.bundleIdentifier())).append("</h1>");
        h.append("<p>Executable: <strong>").append(esc(r.bundleExecutable())).append("</strong>")
         .append(r.bundleTeamId() != null ? " &middot; Team: <strong>" + esc(r.bundleTeamId()) + "</strong>" : "")
         .append("</p>");
        h.append("<div class='hero-meta'>Scan ID: <code style='background:rgba(255,255,255,.15);color:#fff'>")
         .append(esc(r.scanId())).append("</code> &middot; Generated ")
         .append(java.time.LocalDate.now()).append("</div>");
        h.append("</div>");
        return h.toString();
    }

    // ── risk dashboard ────────────────────────────────────────────────────────

    private static String riskDashboard(AnalysisReport r) {
        // Exclude suppressed findings from the report's risk posture
        List<AnalysisReport.VulnerabilityRecord> vulns = activeVulns(r);

        Map<String, Integer> sevCounts = new HashMap<>();
        Map<String, Integer> catCounts = new LinkedHashMap<>();
        catCounts.put("STORAGE", 0);
        catCounts.put("CRYPTO", 0);
        catCounts.put("NETWORK", 0);
        catCounts.put("PLATFORM", 0);
        catCounts.put("AUTH", 0);
        catCounts.put("CODE", 0);
        catCounts.put("RESILIENCE", 0);
        int mstgCount = 0, llmCount = 0;
        for (var v : vulns) {
            String s = v.effectiveSeverity() == null ? "INFO" : v.effectiveSeverity().toUpperCase();
            sevCounts.merge(s, 1, Integer::sum);
            String c = v.category() == null ? "OTHER" : v.category().toUpperCase();
            catCounts.merge(c, 1, Integer::sum);
            if (v.ruleId() != null && v.ruleId().startsWith("LLM-")) llmCount++;
            else mstgCount++;
        }
        int total = vulns.size();
        int crit = sevCounts.getOrDefault("CRITICAL", 0);
        int high = sevCounts.getOrDefault("HIGH", 0);
        int med  = sevCounts.getOrDefault("MEDIUM", 0);
        int low  = sevCounts.getOrDefault("LOW", 0);

        StringBuilder h = new StringBuilder();
        h.append("<div class='card'>");
        h.append("<div class='card-meta'>Risk Posture</div>");
        h.append("<h2>").append(total).append(" finding").append(total == 1 ? "" : "s").append(" detected</h2>");
        h.append("<div class='sev-grid'>");
        h.append(sevTile(crit, "Critical", crit > 0 ? "sev-critical" : "sev-zero"));
        h.append(sevTile(high, "High",     high > 0 ? "sev-high"     : "sev-zero"));
        h.append(sevTile(med,  "Medium",   med  > 0 ? "sev-medium"   : "sev-zero"));
        h.append(sevTile(low,  "Low",      low  > 0 ? "sev-low"      : "sev-zero"));
        h.append(sevTile(total, "Total",   "sev-total"));
        h.append("</div>");

        h.append("<div class='cats'>");
        for (var e : catCounts.entrySet()) {
            if (e.getValue() > 0)
                h.append("<span class='chip'><strong>").append(e.getValue()).append("</strong> ")
                 .append(esc(e.getKey())).append("</span>");
        }
        if (mstgCount > 0)
            h.append("<span class='chip badge-mstg'><strong>").append(mstgCount).append("</strong> MSTG rules</span>");
        if (llmCount > 0)
            h.append("<span class='chip badge-llm'><strong>").append(llmCount).append("</strong> LLM findings</span>");
        h.append("</div>");
        h.append("</div>");
        return h.toString();
    }

    private static String sevTile(int n, String label, String cls) {
        return "<div class='sev-tile " + cls + "'><div class='v'>" + n + "</div><div class='l'>" + label + "</div></div>";
    }

    // ── bundle / signing card ─────────────────────────────────────────────────

    private static String bundleCard(AnalysisReport r) {
        StringBuilder h = new StringBuilder();
        h.append("<div class='card'>");
        h.append("<div class='card-meta'>Bundle &amp; Signing</div>");
        h.append("<div class='kv'>");
        kv(h, "Bundle ID",    r.bundleIdentifier());
        kv(h, "Executable",   r.bundleExecutable());
        kv(h, "Language",     r.isSwift() ? "Swift" : "Objective-C");
        kv(h, "Universal",    r.isUniversal() ? "Yes" : "No");
        kv(h, "Architectures",r.architectures() == null ? "" : String.join(", ", r.architectures()));
        kv(h, "Team ID",      r.bundleTeamId());
        kv(h, "Profile",      r.provisioningProfile());
        kv(h, "Expires",      r.provisioningExpiry());
        kv(h, "Classes",      String.valueOf(r.classCount()));
        kv(h, "Functions",    String.valueOf(r.functionCount()));
        kv(h, "Strings",      String.valueOf(r.stringCount()));
        h.append("</div></div>");
        return h.toString();
    }

    private static void kv(StringBuilder h, String k, String v) {
        if (v == null || v.isBlank()) return;
        h.append("<span class='kv-key'>").append(esc(k)).append("</span>");
        h.append("<span class='kv-val'>").append(esc(v)).append("</span>");
    }

    // ── VULNERABILITIES (the centrepiece) ─────────────────────────────────────

    private static String vulnerabilitiesSection(AnalysisReport r) {
        StringBuilder h = new StringBuilder();
        h.append("<div class='card-meta' style='padding:0 .25rem 0;margin-bottom:.6rem;font-size:.85rem;color:var(--text)'>")
         .append("Vulnerabilities</div>");

        // Active findings only — false_positive / fixed are listed separately further down
        var vulns = activeVulns(r);
        if (vulns == null || vulns.isEmpty()) {
            h.append("<div class='card'><div class='empty empty-good'>")
             .append("✓ No vulnerabilities detected by static rules</div>")
             .append("<p style='text-align:center;color:var(--muted);font-size:.8rem;margin-top:.5rem'>")
             .append("This does not imply absence of bugs. Consider dynamic analysis and manual review.")
             .append("</p></div>");
            return h.toString();
        }

        // sort: effective severity (CRITICAL → LOW) then effective CVSS desc, then rule id
        var sorted = new java.util.ArrayList<>(vulns);
        sorted.sort((a, b) -> {
            int sa = sevRank(a.effectiveSeverity());
            int sb = sevRank(b.effectiveSeverity());
            if (sa != sb) return Integer.compare(sa, sb);
            int cvss = Double.compare(b.effectiveCvssScore(), a.effectiveCvssScore());
            if (cvss != 0) return cvss;
            return String.valueOf(a.ruleId()).compareTo(String.valueOf(b.ruleId()));
        });

        for (var v : sorted) h.append(vulnCard(v));
        return h.toString();
    }

    private static int sevRank(String s) {
        if (s == null) return 5;
        return switch (s.toUpperCase()) {
            case "CRITICAL" -> 0;
            case "HIGH"     -> 1;
            case "MEDIUM"   -> 2;
            case "LOW"      -> 3;
            case "INFO"     -> 4;
            default          -> 5;
        };
    }

    /** Returns only the findings that should appear in the exported report (excludes false_positive & fixed). */
    private static List<AnalysisReport.VulnerabilityRecord> activeVulns(AnalysisReport r) {
        if (r.vulnerabilities() == null) return List.of();
        return r.vulnerabilities().stream().filter(v -> !v.isSuppressed()).toList();
    }

    private static String vulnCard(AnalysisReport.VulnerabilityRecord v) {
        String sev = v.effectiveSeverity() == null ? "INFO" : v.effectiveSeverity().toUpperCase();
        String sevCls = sev.toLowerCase();
        boolean isLlm = v.ruleId() != null && v.ruleId().startsWith("LLM-");
        boolean overridden = v.overrideSeverity() != null && !v.overrideSeverity().isBlank()
                          && !v.overrideSeverity().equalsIgnoreCase(v.severity());

        StringBuilder h = new StringBuilder();
        h.append("<div class='vuln ").append(sevCls).append("'>");

        // head
        h.append("<div class='vuln-head'>");
        h.append("<span class='badge badge-").append(sevCls).append("'>").append(sev).append("</span>");
        h.append("<span class='vuln-cvss'>CVSS ").append(String.format("%.1f", v.effectiveCvssScore())).append("</span>");
        h.append("<div class='vuln-title'>").append(esc(v.title() == null ? "" : v.title())).append("</div>");
        h.append("</div>");
        if (overridden) {
            h.append("<div style='font-size:.72rem;color:var(--muted);margin-bottom:.5rem;font-style:italic'>")
             .append("Severity overridden by reviewer — original was <strong>")
             .append(esc(v.severity())).append("</strong>");
            if (notBlank(v.overrideNote()))
                h.append(" &middot; note: ").append(esc(v.overrideNote()));
            h.append("</div>");
        }

        // sub-meta
        h.append("<div class='vuln-meta' style='margin-bottom:.7rem'>");
        h.append("<span class='vuln-rule'>").append(esc(v.ruleId())).append("</span>");
        if (isLlm) h.append("<span class='badge badge-llm'>LLM</span>");
        else       h.append("<span class='badge badge-mstg'>MSTG</span>");
        if (v.category() != null)  h.append("<span class='chip'>").append(esc(v.category())).append("</span>");
        if (v.cwe() != null && !v.cwe().isBlank()) h.append("<span class='chip'>").append(esc(v.cwe())).append("</span>");
        h.append("</div>");

        // description
        if (notBlank(v.description())) {
            h.append("<div class='vuln-section'>");
            h.append("<div class='vuln-section-title'>Description</div>");
            h.append("<p>").append(esc(v.description())).append("</p>");
            h.append("</div>");
        }

        // affected + evidence side-by-side
        h.append("<div class='vuln-grid'>");
        h.append("<div class='vuln-section'>");
        h.append("<div class='vuln-section-title'>Affected</div>");
        h.append("<div class='kv'>");
        kv(h, "Type",     v.affectedType());
        kv(h, "Name",     v.affectedName());
        kv(h, "Location", v.evidenceLocation());
        h.append("</div></div>");

        h.append("<div class='vuln-section'>");
        h.append("<div class='vuln-section-title'>Evidence</div>");
        h.append("<pre class='code'>").append(esc(v.evidence() == null ? "(no evidence captured)" : v.evidence())).append("</pre>");
        h.append("</div>");
        h.append("</div>");

        // PoC steps
        if (notBlank(v.pocSteps())) {
            h.append("<div class='vuln-section'>");
            h.append("<div class='vuln-section-title'>Proof of Concept &mdash; steps to reproduce</div>");
            h.append("<pre class='code poc'>").append(esc(v.pocSteps())).append("</pre>");
            h.append("</div>");
        }

        // remediation
        if (notBlank(v.remediation())) {
            h.append("<div class='vuln-section'>");
            h.append("<div class='vuln-section-title'>Remediation</div>");
            h.append("<p>").append(esc(v.remediation())).append("</p>");
            h.append("</div>");
        }

        // reference
        if (notBlank(v.referenceUrl())) {
            h.append("<div class='vuln-section'>");
            h.append("<div class='vuln-section-title'>Reference</div>");
            String url = v.referenceUrl();
            if (url.startsWith("http")) {
                h.append("<p><a href='").append(esc(url)).append("' target='_blank' rel='noopener'>")
                 .append(esc(url)).append("</a></p>");
            } else {
                h.append("<p>").append(esc(url)).append("</p>");
            }
            h.append("</div>");
        }

        h.append("</div>");
        return h.toString();
    }

    // ── Suppressed findings (audit trail) ─────────────────────────────────────

    private static String suppressedSection(AnalysisReport r) {
        if (r.vulnerabilities() == null) return "";
        var suppressed = r.vulnerabilities().stream().filter(v -> v.isSuppressed()).toList();
        if (suppressed.isEmpty()) return "";

        StringBuilder h = new StringBuilder();
        h.append("<details>");
        h.append("<summary>Suppressed Findings <span class='secondary'>(")
         .append(suppressed.size()).append(" finding")
         .append(suppressed.size() == 1 ? "" : "s")
         .append(" marked as false positive or fixed — excluded from risk posture)</span></summary>");
        h.append("<div class='details-body'>");
        h.append("<table>");
        h.append("<tr><th>Status</th><th>Rule</th><th>Title</th><th>Original Severity</th><th>Reviewer Note</th></tr>");
        for (var v : suppressed) {
            String statusLabel = "false_positive".equalsIgnoreCase(v.status()) ? "False Positive"
                               : "fixed".equalsIgnoreCase(v.status())          ? "Fixed"
                               : v.status();
            h.append("<tr style='opacity:.7'>");
            h.append("<td><span class='badge badge-info'>").append(esc(statusLabel)).append("</span></td>");
            h.append("<td class='mono'>").append(esc(v.ruleId())).append("</td>");
            h.append("<td>").append(esc(v.title())).append("</td>");
            h.append("<td>").append(esc(v.severity())).append("</td>");
            h.append("<td>").append(esc(v.overrideNote() == null ? "" : v.overrideNote())).append("</td>");
            h.append("</tr>");
        }
        h.append("</table></div></details>");
        return h.toString();
    }

    // ── LLM raw findings (only when notable) ──────────────────────────────────

    private static String llmRawSection(AnalysisReport r) {
        if (r.llmFindings() == null || r.llmFindings().isEmpty()) return "";
        // Filter to ones that actually mention a severity tag — others are noise (NONE / per-fn summaries).
        var withSeverity = r.llmFindings().stream()
                .filter(f -> f.finding() != null && hasSeverityKeyword(f.finding()))
                .toList();
        if (withSeverity.isEmpty()) return "";

        StringBuilder h = new StringBuilder();
        h.append("<details>");
        h.append("<summary>Raw LLM Findings <span class='secondary'>(")
         .append(withSeverity.size()).append(" function").append(withSeverity.size() == 1 ? "" : "s")
         .append(" flagged — vulnerabilities above are already distilled from these)</span></summary>");
        h.append("<div class='details-body'><table>");
        h.append("<tr><th>Class</th><th>Function</th><th>Mode</th><th>Finding (truncated)</th></tr>");
        for (var f : withSeverity) {
            String snippet = f.finding();
            if (snippet.length() > 400) snippet = snippet.substring(0, 400) + "…";
            h.append("<tr><td class='mono'>").append(esc(f.className()))
             .append("</td><td class='mono'>").append(esc(f.functionName()))
             .append("</td><td>").append(esc(f.mode()))
             .append("</td><td><pre class='code'>").append(esc(snippet)).append("</pre></td></tr>");
        }
        h.append("</table></div></details>");
        return h.toString();
    }

    // ── code surface (compact, collapsible) ───────────────────────────────────

    private static String codeSurfaceSection(AnalysisReport r) {
        StringBuilder h = new StringBuilder();
        h.append("<details>");
        h.append("<summary>Code Surface <span class='secondary'>(")
         .append(r.classCount()).append(" classes &middot; ")
         .append(r.functionCount()).append(" functions &middot; ")
         .append(r.entryPoints() == null ? 0 : r.entryPoints().size())
         .append(" entry points)</span></summary>");
        h.append("<div class='details-body'>");

        if (r.entryPoints() != null && !r.entryPoints().isEmpty()) {
            h.append("<div class='vuln-section-title'>Entry Points</div>");
            h.append("<ul style='font-family:ui-monospace,monospace;font-size:.78rem;margin-bottom:1rem'>");
            for (String ep : r.entryPoints()) h.append("<li>").append(esc(ep)).append("</li>");
            h.append("</ul>");
        }

        if (r.classes() != null && !r.classes().isEmpty()) {
            h.append("<div class='vuln-section-title'>Class Index (top ")
             .append(MAX_CLASSES_DISPLAY).append(" by function count)</div>");
            h.append("<div class='class-grid'>");
            r.classes().entrySet().stream()
                .sorted((a, b) -> Integer.compare(b.getValue().size(), a.getValue().size()))
                .limit(MAX_CLASSES_DISPLAY)
                .forEach(e -> h.append("<div class='class-row'><span>").append(esc(e.getKey()))
                                  .append("</span><span class='n'>").append(e.getValue().size())
                                  .append(" fn</span></div>"));
            h.append("</div>");
            if (r.classes().size() > MAX_CLASSES_DISPLAY) {
                h.append("<p style='color:var(--muted);font-size:.75rem;margin-top:.5rem'>… ")
                 .append(r.classes().size() - MAX_CLASSES_DISPLAY)
                 .append(" more classes available in the API: <code>/api/v1/scans/{id}/functions</code></p>");
            }
        }
        h.append("</div></details>");
        return h.toString();
    }

    // ── sample strings (collapsible) ──────────────────────────────────────────

    private static String stringsSampleSection(AnalysisReport r) {
        if (r.strings() == null || r.strings().isEmpty()) return "";
        StringBuilder h = new StringBuilder();
        h.append("<details>");
        h.append("<summary>String Sample <span class='secondary'>(")
         .append(r.stringCount()).append(" total &middot; showing first ")
         .append(Math.min(MAX_STRINGS_DISPLAY, r.strings().size())).append(")</span></summary>");
        h.append("<div class='details-body'>");
        h.append("<table><tr><th>Address</th><th>Segment</th><th>Value</th></tr>");
        int shown = 0;
        for (var s : r.strings()) {
            if (shown++ >= MAX_STRINGS_DISPLAY) break;
            h.append("<tr><td class='mono'>").append(esc(s.address()))
             .append("</td><td>").append(esc(s.segment()))
             .append("</td><td class='mono'>").append(esc(s.value())).append("</td></tr>");
        }
        h.append("</table>");
        if (r.stringCount() > MAX_STRINGS_DISPLAY) {
            h.append("<p style='color:var(--muted);font-size:.75rem;margin-top:.5rem'>… full string table available via API: <code>/api/v1/scans/{id}/strings</code></p>");
        }
        h.append("</div></details>");
        return h.toString();
    }

    // ── utils ─────────────────────────────────────────────────────────────────

    private static boolean notBlank(String s) { return s != null && !s.isBlank(); }

    private static boolean hasSeverityKeyword(String s) {
        if (s == null) return false;
        String u = s.toUpperCase();
        return u.contains("HIGH") || u.contains("MEDIUM") || u.contains("CRITICAL") || u.contains("LOW");
    }

    private static String esc(String s) {
        if (s == null) return "";
        return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                .replace("\"", "&quot;");
    }
}
